export const D4_BUILDING_ID = "D4_ENGINEERING_3";

export const D4_ELEMENT_IDS = ["BLD_D3", "BLD_D4"];

export const D4_BUILDING = {
  id: D4_BUILDING_ID,
  name: "D4 공대 3호관",
  displayName: "D4 / 공대 3호관",
  elementIds: D4_ELEMENT_IDS,
  roofArea: 980,
  source: {
    path: "docs/d4.pdf",
    note: "손그림 구조도를 바탕으로 한 목업 seed. 프론트 담당자가 추후 실제 구조도로 교체 예정.",
  },
  floors: [
    { id: "1F", floor: 1, label: "1층", sourcePages: [3, 4] },
    { id: "2F", floor: 2, label: "2층", sourcePages: [5, 10] },
    { id: "3F", floor: 3, label: "3층", sourcePages: [6, 7] },
    { id: "4F", floor: 4, label: "4층", sourcePages: [8, 9] },
    { id: "5F", floor: 5, label: "5층", sourcePages: [1, 2] },
    { id: "6F", floor: 6, label: "6층", sourcePages: [2] },
  ],
  wings: [
    { id: "left", label: "왼쪽 동", floors: 5, x: -2.25, width: 3.2, depth: 4.2 },
    { id: "right", label: "오른쪽 동", floors: 6, x: 2.25, width: 3.2, depth: 4.2 },
  ],
  bridges: [
    { id: "bridge-3f", floor: 3, label: "3층 연결 다리" },
    { id: "bridge-5f", floor: 5, label: "5층 연결 다리" },
  ],
};

const COMMON_SOURCE = {
  sourcePath: "docs/d4.pdf",
  sourceConfidence: "medium",
};

const DETAILED_ROOM_NUMBERS = new Set([
  "101",
  "102",
  "103",
  "108",
  "204",
  "207",
  "305",
  "309",
  "314",
  "401",
  "411",
  "501",
  "601",
]);

function getMockGeometry(floor, side, index) {
  const wingX = side === "left" ? -2.25 : 2.25;
  const colOffset = index % 2 === 0 ? -0.48 : 0.48;
  const rowOffset = index % 4 < 2 ? -0.85 : 0.85;

  return {
    x: wingX + colOffset,
    z: rowOffset,
    width: 0.96 + (floor % 2) * 0.12,
    depth: 0.92,
  };
}

function createMockRoom({
  roomNumber,
  floor,
  side,
  index,
  specialType = "lecture",
  size = "small",
  sourcePage,
  sourceNote,
}) {
  return {
    id: `D4-${roomNumber}`,
    roomNumber,
    name: `D4 ${roomNumber} ${specialType === "faculty" ? "교수/조교실" : "목업실"}`,
    floor,
    side,
    size,
    airConditioners: specialType === "lecture" && size !== "small" ? 2 : 1,
    hasLargeScreen: specialType === "lecture",
    specialType,
    geometry: getMockGeometry(floor, side, index),
    timetable: [],
    ...COMMON_SOURCE,
    sourceConfidence: "low",
    sourcePage,
    sourceNote,
  };
}

const ADDITIONAL_ROOM_SEEDS = [
  ...["104", "105", "106", "107"].map((roomNumber, index) => ({
    roomNumber,
    floor: 1,
    side: "left",
    index,
    sourcePage: 4,
    sourceNote: "1층 왼쪽 동 PDF에서 호실 번호 판독. 용도는 추후 보정 필요.",
  })),
  ...["109", "110", "111", "112", "113", "114"].map((roomNumber, index) => ({
    roomNumber,
    floor: 1,
    side: roomNumber === "114" ? "left" : "right",
    index,
    sourcePage: 3,
    sourceNote: "1층 다른 면 PDF에서 호실 번호 판독. 용도는 추후 보정 필요.",
  })),
  ...["201", "202", "203"].map((roomNumber, index) => ({
    roomNumber,
    floor: 2,
    side: "right",
    index,
    sourcePage: 5,
    sourceNote: "2층 오른쪽 동 PDF에서 호실 번호 판독.",
  })),
  ...["205", "206", "208", "209"].map((roomNumber, index) => ({
    roomNumber,
    floor: 2,
    side: Number(roomNumber) >= 208 ? "left" : "left",
    index,
    sourcePage: Number(roomNumber) >= 208 ? 10 : 5,
    sourceNote: "2층 왼쪽 동 PDF에서 호실 번호 판독.",
  })),
  ...["210", "212", "213", "214", "215", "216"].map((roomNumber, index) => ({
    roomNumber,
    floor: 2,
    side: "right",
    index,
    specialType: "faculty",
    sourcePage: 10,
    sourceNote: "2층 오른쪽 동 교수실 구역으로 판독. 교수명은 미정.",
  })),
  {
    roomNumber: "211",
    floor: 2,
    side: "right",
    index: 6,
    size: "medium",
    sourcePage: 10,
    sourceNote: "2층 오른쪽 동 의사소통/세미나 성격 공간으로 보이는 목업실.",
  },
  ...["301", "302", "303", "304"].map((roomNumber, index) => ({
    roomNumber,
    floor: 3,
    side: "right",
    index,
    specialType: Number(roomNumber) >= 302 ? "faculty" : "lecture",
    sourcePage: 6,
    sourceNote: "3층 오른쪽 동 PDF에서 호실 번호 판독.",
  })),
  ...["306", "307", "308"].map((roomNumber, index) => ({
    roomNumber,
    floor: 3,
    side: "left",
    index,
    specialType: "faculty",
    sourcePage: 6,
    sourceNote: "3층 왼쪽 동 PDF에서 호실 번호 판독.",
  })),
  {
    roomNumber: "310",
    floor: 3,
    side: "left",
    index: 4,
    specialType: "lab",
    size: "medium",
    sourcePage: 7,
    sourceNote: "3층 왼쪽 동 실험/장비 공간으로 보이는 목업실.",
  },
  ...["311", "312", "313", "315", "316", "317"].map((roomNumber, index) => ({
    roomNumber,
    floor: 3,
    side: "right",
    index,
    specialType: "faculty",
    sourcePage: 7,
    sourceNote: "3층 오른쪽 동 교수실 구역으로 판독. 교수명은 미정.",
  })),
  ...["402", "403", "404"].map((roomNumber, index) => ({
    roomNumber,
    floor: 4,
    side: "right",
    index,
    specialType: roomNumber === "404" ? "server" : "lecture",
    size: roomNumber === "402" ? "medium" : "small",
    sourcePage: 8,
    sourceNote: "4층 오른쪽 동 PDF에서 호실 번호 판독.",
  })),
  ...["405", "406", "407", "408", "409"].map((roomNumber, index) => ({
    roomNumber,
    floor: 4,
    side: "left",
    index,
    sourcePage: 8,
    sourceNote: "4층 왼쪽 동 PDF에서 호실 번호 판독.",
  })),
  {
    roomNumber: "410",
    floor: 4,
    side: "left",
    index: 5,
    size: "medium",
    sourcePage: 9,
    sourceNote: "4층 왼쪽 동 410 계열 공간으로 판독.",
  },
  ...["412", "413", "414"].map((roomNumber, index) => ({
    roomNumber,
    floor: 4,
    side: "right",
    index,
    specialType: "faculty",
    sourcePage: 9,
    sourceNote: "4층 오른쪽 동 교수실 구역으로 판독. 교수명은 미정.",
  })),
  ...["502", "503", "504", "505", "506"].map((roomNumber, index) => ({
    roomNumber,
    floor: 5,
    side: "left",
    index,
    specialType: "faculty",
    sourcePage: 1,
    sourceNote: "5층 왼쪽 동 PDF에서 번호/구획 판독. 용도는 교수/연구실로 가정.",
  })),
  {
    roomNumber: "507",
    floor: 5,
    side: "right",
    index: 0,
    size: "medium",
    sourcePage: 2,
    sourceNote: "5층 오른쪽 동 PDF에서 구획 판독. 번호는 목업용 보강.",
  },
];

const ADDITIONAL_D4_ROOMS = ADDITIONAL_ROOM_SEEDS.filter(
  (room) => !DETAILED_ROOM_NUMBERS.has(room.roomNumber),
).map(createMockRoom);

export const D4_ROOMS = [
  {
    id: "D4-101",
    roomNumber: "101",
    name: "D4 101 강의실",
    floor: 1,
    side: "right",
    size: "large",
    airConditioners: 3,
    hasLargeScreen: true,
    specialType: "lecture",
    geometry: { x: 1.55, z: -1.05, width: 1.25, depth: 1.1 },
    timetable: [
      { day: "월", startHour: 9, durationHours: 3, subject: "자료구조", professorId: "kim" },
      { day: "수", startHour: 13, durationHours: 3, subject: "컴퓨터구조", professorId: "park" },
    ],
    ...COMMON_SOURCE,
    sourcePage: 4,
    sourceNote: "1층 우측 블록 101. 용도는 발표용 가정 데이터.",
  },
  {
    id: "D4-102",
    roomNumber: "102",
    name: "D4 102 세미나실",
    floor: 1,
    side: "right",
    size: "medium",
    airConditioners: 2,
    hasLargeScreen: true,
    specialType: "lecture",
    geometry: { x: 2.55, z: -1.05, width: 1.05, depth: 1.1 },
    timetable: [
      { day: "화", startHour: 10, durationHours: 2, subject: "캡스톤 세미나", professorId: "lee" },
      { day: "목", startHour: 14, durationHours: 2, subject: "졸업작품 회의" },
    ],
    ...COMMON_SOURCE,
    sourcePage: 4,
    sourceNote: "1층 우측 블록 102. PDF 손글씨 기반 목업.",
  },
  {
    id: "D4-103",
    roomNumber: "103",
    name: "D4 103 강의실",
    floor: 1,
    side: "right",
    size: "medium",
    airConditioners: 2,
    hasLargeScreen: true,
    specialType: "lecture",
    geometry: { x: 2.0, z: 0.55, width: 1.45, depth: 1.1 },
    timetable: [
      { day: "월", startHour: 13, durationHours: 2, subject: "공학설계입문", professorId: "park" },
      { day: "금", startHour: 10, durationHours: 2, subject: "알고리즘" },
    ],
    ...COMMON_SOURCE,
    sourcePage: 4,
    sourceNote: "1층 우측 블록 103. 용도는 강의실로 가정.",
  },
  {
    id: "D4-108",
    roomNumber: "108",
    name: "D4 108 컴퓨터실",
    floor: 1,
    side: "left",
    size: "large",
    airConditioners: 4,
    hasLargeScreen: true,
    specialType: "computer_lab",
    computerCount: 36,
    geometry: { x: -2.25, z: 0.85, width: 1.65, depth: 1.35 },
    timetable: [
      { day: "월", startHour: 14, durationHours: 3, subject: "프로그래밍 실습", professorId: "kim" },
      { day: "수", startHour: 9, durationHours: 3, subject: "데이터베이스 실습", professorId: "lee" },
    ],
    ...COMMON_SOURCE,
    sourcePage: 4,
    sourceNote: "1층 좌측 108 표기를 컴퓨터실 목업으로 지정.",
  },
  {
    id: "D4-204",
    roomNumber: "204",
    name: "D4 204 강의실",
    floor: 2,
    side: "left",
    size: "medium",
    airConditioners: 2,
    hasLargeScreen: true,
    specialType: "lecture",
    geometry: { x: -2.65, z: -0.8, width: 1.25, depth: 1.2 },
    timetable: [
      { day: "화", startHour: 9, durationHours: 3, subject: "인공지능", professorId: "lee" },
      { day: "목", startHour: 10, durationHours: 2, subject: "웹프로그래밍", professorId: "kim" },
    ],
    ...COMMON_SOURCE,
    sourcePage: 5,
    sourceNote: "2층 좌측 204 계열 방. 강의실로 가정.",
  },
  {
    id: "D4-207",
    roomNumber: "207",
    name: "D4 207 실험실",
    floor: 2,
    side: "left",
    size: "medium",
    airConditioners: 2,
    hasLargeScreen: true,
    specialType: "lab",
    geometry: { x: -1.75, z: 0.8, width: 1.35, depth: 1.2 },
    timetable: [
      { day: "화", startHour: 14, durationHours: 3, subject: "네트워크 실습", professorId: "park" },
      { day: "금", startHour: 13, durationHours: 3, subject: "IoT 실험" },
    ],
    ...COMMON_SOURCE,
    sourcePage: 5,
    sourceNote: "2층 좌측 207 인근 공간. 실험실로 가정.",
  },
  {
    id: "D4-305",
    roomNumber: "305",
    name: "D4 305 서버 장비실",
    floor: 3,
    side: "left",
    size: "small",
    airConditioners: 2,
    hasLargeScreen: false,
    specialType: "server",
    geometry: { x: -2.65, z: -0.8, width: 1.1, depth: 1.1 },
    timetable: [],
    ...COMMON_SOURCE,
    sourceConfidence: "low",
    sourcePage: 6,
    sourceNote: "3층 좌측 305. 서버/장비실 여부는 발표용 가정.",
  },
  {
    id: "D4-309",
    roomNumber: "309",
    name: "D4 309 실험실",
    floor: 3,
    side: "left",
    size: "medium",
    airConditioners: 2,
    hasLargeScreen: true,
    specialType: "lab",
    geometry: { x: -1.7, z: 0.8, width: 1.35, depth: 1.1 },
    timetable: [
      { day: "수", startHour: 14, durationHours: 3, subject: "임베디드 실험", professorId: "park" },
    ],
    ...COMMON_SOURCE,
    sourcePage: 7,
    sourceNote: "3층 우측 309 인근 공간. 실험실로 가정.",
  },
  {
    id: "D4-314",
    roomNumber: "314",
    name: "박교수 연구실",
    floor: 3,
    side: "right",
    size: "small",
    airConditioners: 1,
    hasLargeScreen: false,
    specialType: "faculty",
    professorId: "park",
    geometry: { x: 2.55, z: 0.85, width: 1.1, depth: 1.0 },
    timetable: [
      { day: "목", startHour: 15, durationHours: 2, subject: "프로젝트 지도" },
    ],
    ...COMMON_SOURCE,
    sourcePage: 7,
    sourceNote: "3층 우측 교수실 구역. 교수명은 시뮬레이션용.",
  },
  {
    id: "D4-401",
    roomNumber: "401",
    name: "D4 401 대형 세미나실",
    floor: 4,
    side: "right",
    size: "large",
    airConditioners: 4,
    hasLargeScreen: true,
    specialType: "lecture",
    geometry: { x: 1.75, z: -0.75, width: 1.6, depth: 1.25 },
    timetable: [
      { day: "화", startHour: 13, durationHours: 2, subject: "초청 세미나" },
      { day: "금", startHour: 15, durationHours: 2, subject: "졸업작품 발표" },
    ],
    ...COMMON_SOURCE,
    sourcePage: 8,
    sourceNote: "4층 우측 401/402 계열 공간. 대형 세미나실 가정.",
  },
  {
    id: "D4-411",
    roomNumber: "411",
    name: "김교수 연구실",
    floor: 4,
    side: "right",
    size: "small",
    airConditioners: 1,
    hasLargeScreen: false,
    specialType: "faculty",
    professorId: "kim",
    geometry: { x: 2.75, z: 0.85, width: 1.0, depth: 1.0 },
    timetable: [
      { day: "월", startHour: 10, durationHours: 2, subject: "상담/지도" },
      { day: "수", startHour: 15, durationHours: 2, subject: "연구 미팅" },
    ],
    ...COMMON_SOURCE,
    sourcePage: 9,
    sourceNote: "4층 우측 교수실 구역. 교수명은 시뮬레이션용.",
  },
  {
    id: "D4-501",
    roomNumber: "501",
    name: "D4 501 프로젝트실",
    floor: 5,
    side: "left",
    size: "medium",
    airConditioners: 2,
    hasLargeScreen: true,
    specialType: "lecture",
    geometry: { x: -2.25, z: 0.75, width: 1.55, depth: 1.25 },
    timetable: [
      { day: "목", startHour: 9, durationHours: 3, subject: "캡스톤디자인", professorId: "kim" },
    ],
    ...COMMON_SOURCE,
    sourceConfidence: "low",
    sourcePage: 1,
    sourceNote: "5층 좌측 공간. 호실/용도는 목업용 가정.",
  },
  {
    id: "D4-601",
    roomNumber: "601",
    name: "D4 601 우측동 교수/조교실",
    floor: 6,
    side: "right",
    size: "small",
    airConditioners: 1,
    hasLargeScreen: false,
    specialType: "faculty",
    professorId: "lee",
    geometry: { x: 2.35, z: -0.15, width: 1.35, depth: 1.1 },
    timetable: [
      { day: "화", startHour: 15, durationHours: 2, subject: "연구 미팅" },
    ],
    ...COMMON_SOURCE,
    sourceConfidence: "low",
    sourcePage: 2,
    sourceNote: "사진 기준 오른쪽 동은 6층까지 있는 구조를 반영한 목업 공간.",
  },
  ...ADDITIONAL_D4_ROOMS,
];

export const D4_BUILDING_DATA = {
  ...D4_BUILDING,
  rooms: D4_ROOMS,
};

export function isD4ElementId(elementId) {
  return D4_ELEMENT_IDS.includes(elementId);
}

export function getD4RoomById(roomId) {
  return D4_ROOMS.find((room) => room.id === roomId) ?? D4_ROOMS[0];
}
