/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Untitled.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.학교001.geometry}
          material={materials["sandybrown.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.학교001_1.geometry}
          material={materials["lightgreen.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.학교001_2.geometry}
          material={materials["Blacktop_Old_01.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.학교001_3.geometry}
          material={materials["red.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.학교001_4.geometry}
          material={materials["FrontColor.003"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh423.geometry}
        material={materials["lightgreen.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh423_1.geometry}
        material={materials["Blacktop_Old_01.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh423_2.geometry}
        material={materials["FrontColor.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh423_3.geometry}
        material={materials["red.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh423_4.geometry}
        material={materials["sandybrown.002"]}
      />
    </group>
  );
}

useGLTF.preload("/Untitled.glb");
